import { test, expect } from '@playwright/test';
import { entrar, isolado } from './apoio.js';
import { registrar } from './fase4-modal-helper.js';

function dia(dias = 0) { return new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: '2-digit', year: '2-digit' }).format(new Date(Date.now() + dias * 86400000)); }

test('BTN Agenda: linhas, detalhes, ações Fonada e Ao Vivo', async ({ page, request }) => {
  test.setTimeout(90000);
  test.skip(!isolado, 'Exige banco QA isolado.');
  await entrar(page);
  const headers = { Authorization: `Bearer ${await page.evaluate(() => localStorage.getItem('pombo_token'))}` };
  const nome = `TESTE_QA_AGENDA_FINAL_${Date.now()}`;
  const criado = await request.post('/api/clientes', { headers, data: { nome } });
  expect(criado.status()).toBe(201); const cliente = await criado.json();
  let fonada, aoVivo, lembrete;
  try {
    const fo = await request.post('/api/fonadas', { headers, data: { cliente_id: cliente.id, valor: 20, cobranca: dia(2), periodo: 'MANHÃ', p1_dia: dia(), p1_para: `QA DESTINATARIO ${nome}`, p1_tema: 'QA' } });
    expect(fo.status()).toBe(201); fonada = await fo.json();
    const av = await request.post('/api/ao-vivo', { headers, data: { cliente_id: cliente.id, valor: 20, dia_entrega: dia(), para: `QA DESTINATARIO ${nome}` } });
    expect(av.status()).toBe(201); aoVivo = await av.json();
    const dataIso = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
    const le = await request.post('/api/agenda/lembretes', { headers, data: { titulo: `QA LEMBRETE ${nome}`, data: dataIso } });
    expect(le.status()).toBe(201); lembrete = await le.json();
    await page.goto('/agenda');
    await expect(page.locator('.linha-agenda').filter({ hasText: nome })).toHaveCount(3);
    const cards = page.locator('.faixa-semana-agenda button');
    await cards.nth(1).click();
    await expect(cards.nth(1)).toHaveClass(/ativo/);
    registrar('BTN-046', page, '.faixa-semana-agenda button:nth-child(2)', 'selecionar dia da semana', 'dia ativo alterado');
    await page.getByRole('button', { name: 'Hoje', exact: true }).first().click();
    const linhaFonada = page.locator('.linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Fonada' });
    await linhaFonada.click();
    await expect(page.locator('.agenda-detalhe-fonada')).toBeVisible();
    registrar('BTN-038', page, '.linha-agenda:has-text("Fonada")', 'selecionar linha', 'detalhes Fonada exibidos');
    await page.getByRole('button', { name: 'Não atendeu', exact: true }).click();
    await expect(page.getByRole('dialog', { name: new RegExp(`Não atendeu — ${nome}`) })).toBeVisible();
    registrar('BTN-068', page, 'button:has-text("Não atendeu")', 'abrir remarcação', 'diálogo de tentativa aberto');
    await page.getByRole('dialog').getByRole('button', { name: 'Cancelar' }).click();
    await page.getByRole('button', { name: 'Marcar passada' }).click();
    await page.getByRole('button', { name: /Concluídos/ }).click();
    await page.locator('.agenda-concluidos .linha-agenda').filter({ hasText: nome }).click();
    await expect(page.getByRole('button', { name: 'Desfazer', exact: true })).toBeVisible();
    registrar('BTN-069', page, 'button:has-text("Marcar passada")', 'dar baixa', 'ação Desfazer disponível');
    await page.getByRole('button', { name: 'Desfazer', exact: true }).click();
    await page.locator('.ag-time-group > .linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Fonada' }).click();
    await expect(page.getByRole('button', { name: 'Marcar passada' })).toBeVisible();
    registrar('BTN-070', page, 'button:has-text("Desfazer")', 'desfazer baixa', 'ação Marcar passada restaurada');
    await page.getByRole('button', { name: 'Ver cliente' }).click();
    await expect(page).toHaveURL(new RegExp(`/clientes/${cliente.id}$`));
    registrar('BTN-066', page, '.agenda-detalhe-fonada button:has-text("Ver cliente")', 'abrir ficha', 'ficha correta aberta');
    await page.goto('/agenda');
    await page.locator('.linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Fonada' }).click();
    await page.getByRole('button', { name: 'Abrir pedido' }).click();
    await expect(page).toHaveURL(new RegExp(`/fonada/${fonada.id}$`));
    registrar('BTN-067', page, '.agenda-detalhe-fonada button:has-text("Abrir pedido")', 'abrir pedido', 'Fonada correta aberta');
    await page.goto('/agenda');
    await page.locator('.linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Ao vivo' }).click();
    await expect(page.locator('.agenda-detalhe-aovivo')).toBeVisible();
    registrar('BTN-039', page, '.linha-agenda:has-text("Ao vivo")', 'selecionar linha', 'detalhes Ao Vivo exibidos');
    await page.getByRole('button', { name: 'Ver cliente' }).click();
    await expect(page).toHaveURL(new RegExp(`/clientes/${cliente.id}$`));
    registrar('BTN-073', page, '.agenda-detalhe-aovivo button:has-text("Ver cliente")', 'abrir ficha', 'ficha correta aberta');
    await page.goto('/agenda');
    await page.locator('.linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Ao vivo' }).click();
    await page.getByRole('button', { name: 'Abrir pedido' }).click();
    await expect(page).toHaveURL(new RegExp(`/ao-vivo/${aoVivo.id}$`));
    registrar('BTN-074', page, '.agenda-detalhe-aovivo button:has-text("Abrir pedido")', 'abrir pedido', 'Ao Vivo correto aberto');
    await page.goto('/agenda');
    await page.locator('.linha-agenda').filter({ hasText: `QA LEMBRETE ${nome}` }).click();
    await expect(page.getByRole('button', { name: 'Marcar concluído' })).toBeVisible();
    registrar('BTN-040', page, '.linha-agenda:has-text("QA LEMBRETE")', 'selecionar linha', 'detalhes do lembrete exibidos');
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole('dialog', { name: 'Detalhes do compromisso' })).toHaveCount(0);
    await page.locator('.linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Fonada' }).click();
    await expect(page.getByRole('button', { name: 'Fechar detalhes' })).toBeVisible();
    await page.getByRole('button', { name: 'Fechar detalhes' }).click();
    await expect(page.getByRole('dialog', { name: 'Detalhes do compromisso' })).toHaveCount(0);
    registrar('BTN-055', page, 'button[aria-label="Fechar detalhes"]', 'fechar painel móvel', 'detalhes recolhidos');
    await page.locator('.linha-agenda').filter({ hasText: nome }).filter({ hasText: 'Fonada' }).click();
    await page.locator('.drawer-overlay-mobile').click({ position: { x: 2, y: 2 } });
    await expect(page.getByRole('dialog', { name: 'Detalhes do compromisso' })).toHaveCount(0);
    registrar('BTN-056', page, '.drawer-overlay-mobile', 'clicar fora do painel', 'detalhes recolhidos');
  } finally {
    if (lembrete) await request.delete(`/api/agenda/lembretes/${lembrete.id}`, { headers });
    if (aoVivo) await request.delete(`/api/ao-vivo/${aoVivo.id}`, { headers });
    if (fonada) await request.delete(`/api/fonadas/${fonada.id}`, { headers });
    await request.delete(`/api/clientes/${cliente.id}`, { headers });
    await request.delete(`/api/clientes/${cliente.id}/definitivo`, { headers });
  }
});
